In [2]:
import os
import pandas as pd

# Directorio actual
folder_path = '.'

# Obtener lista de archivos CSV y XLSX
files = [f for f in os.listdir(folder_path) if f.endswith('.csv') or f.endswith('.xlsx')]

print(f"=== SE ENCONTRARON {len(files)} ARCHIVOS PARA ANALIZAR ===\n")

for file_name in files:
    full_path = os.path.join(folder_path, file_name)
    size_mb = os.path.getsize(full_path) / (1024 * 1024)
    print("=" * 80)
    print(f"📄 ARCHIVO: {file_name} ({size_mb:.2f} MB)")
    print("=" * 80)
    
    try:
        # Cargar una muestra reducida (50 filas) para no saturar la memoria RAM en la inspección
        if file_name.endswith('.csv'):
            # Probar con encoding utf-8 o latin-1 por si hay tildes/caracteres de Colombia
            try:
                df_sample = pd.read_csv(full_path, nrows=50, low_memory=False)
            except UnicodeDecodeError:
                df_sample = pd.read_csv(full_path, nrows=50, encoding='latin-1', low_memory=False)
        else:
            df_sample = pd.read_excel(full_path, nrows=50)
            
        print(f"📌 Total de columnas: {len(df_sample.columns)}")
        print("📌 Lista de columnas:")
        for idx, col in enumerate(df_sample.columns, 1):
            print(f"   {idx}. {col}")
            
        print("\n🔍 Primeras 2 filas de muestra:")
        display(df_sample.head(2))
        
    except Exception as e:
        print(f"❌ Error al leer el archivo {file_name}: {e}")
        
    print("\n")

=== SE ENCONTRARON 7 ARCHIVOS PARA ANALIZAR ===

================================================================================
📄 ARCHIVO: 3._Accidentes_de_Transito_ocurridos_en_el_Municipio_de_Bucaramanga_20260926.csv (8.38 MB)
================================================================================
📌 Total de columnas: 24
📌 Lista de columnas:
   1. ORDEN
   2. FECHA
   3. AÑO
   4. MES
   5. DÍA
   6. GRAVEDAD
   7. PEATON
   8. AUTOMOVIL
   9. CAMPERO
   10. CAMIONETA
   11. MICRO
   12. BUSETA
   13. BUS
   14. CAMION
   15. VOLQUETA
   16. MOTO
   17. BICICLETA
   18. OTRO
   19. BARRIO
   20. HORA
   21. ENTIDAD
   22. COMUNA
   23. Propietario de Vehículo
   24. DIURNIO/NOCTURNO

🔍 Primeras 2 filas de muestra:

,ORDEN,FECHA,AÑO,MES,DÍA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPERO,CAMIONETA,...,VOLQUETA,MOTO,BICICLETA,OTRO,BARRIO,HORA,ENTIDAD,COMUNA,Propietario de Vehículo,DIURNIO/NOCTURNO
0,1,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Con heridos,0,1,0,0,...,0,0,0,0,Mutis,1899-12-31T12:15:00.000,AGENTES DTB,17. MUTIS,Particular,Diurno
1,2,2012-01-01T00:00:00.000,2012,01. Enero,07. Domingo,Solo daños,0,1,0,1,...,0,0,0,0,Regaderos Norte,1899-12-31T14:00:00.000,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno

================================================================================
📄 ARCHIVO: Accidentalidad_en_Barranquilla_20260926.csv (3.05 MB)
================================================================================
📌 Total de columnas: 11
📌 Lista de columnas:
   1. FECHA_ACCIDENTE
   2. HORA_ACCIDENTE
   3. GRAVEDAD_ACCIDENTE
   4. CLASE_ACCIDENTE
   5. SITIO_EXACTO_ACCIDENTE
   6. CANT_HERIDOS_EN _SITIO_ACCIDENTE
   7. CANT_MUERTOS_EN _SITIO_ACCIDENTE
   8. CANTIDAD_ACCIDENTES
   9. AÑO_ACCIDENTE
   10. MES_ACCIDENTE
   11. DIA_ACCIDENTE

🔍 Primeras 2 filas de muestra:

,FECHA_ACCIDENTE,HORA_ACCIDENTE,GRAVEDAD_ACCIDENTE,CLASE_ACCIDENTE,SITIO_EXACTO_ACCIDENTE,CANT_HERIDOS_EN _SITIO_ACCIDENTE,CANT_MUERTOS_EN _SITIO_ACCIDENTE,CANTIDAD_ACCIDENTES,AÑO_ACCIDENTE,MES_ACCIDENTE,DIA_ACCIDENTE
0,2018-01-01T00:00:00.000,01:30:00:am,Con heridos,Atropello,CL 87 9H 24,1.0,NaN,1,2018,January,Mon
1,2018-01-01T00:00:00.000,02:00:00:pm,Solo daños,Choque,CL 110 CR 46,NaN,NaN,1,2018,January,Mon

================================================================================
📄 ARCHIVO: Accidentalidad_Municipio_de__Envigado_20260926.csv (13.81 MB)
================================================================================
📌 Total de columnas: 17
📌 Lista de columnas:
   1. RADICADO
   2. FECHA
   3. HORA
   4. DÍA DE LA SEMANA
   5. CLASE DE VEHICULO
   6. TIPO DE SERVICIO
   7. TIPO DE VICTIMA
   8. SEXO
   9. ESTADO DE BEODEZ
   10. RESULTADO DE BEODEZ
   11. GRAVEDAD
   12. CLASE DE ACCIDENTE
   13. CAUSA
   14. DIRECCIÓN
   15. BARRIO
   16. AREA
   17. Coordenadas

🔍 Primeras 2 filas de muestra:

,RADICADO,FECHA,HORA,DÍA DE LA SEMANA,CLASE DE VEHICULO,TIPO DE SERVICIO,TIPO DE VICTIMA,SEXO,ESTADO DE BEODEZ,RESULTADO DE BEODEZ,GRAVEDAD,CLASE DE ACCIDENTE,CAUSA,DIRECCIÓN,BARRIO,AREA,Coordenadas
0,2134024,1/01/2014,10:30:00 p. m.,Miércoles,NaN,NaN,NaN,NaN,0,0,SOLO DAÑOS,CHOQUE,Otra-Conductor,NaN,LAS FLORES,URBANA,POINT (-75.57921612 6.172014741)
1,2134024,1/01/2014,10:30:00 p. m.,Miércoles,NaN,NaN,NaN,NaN,0,0,HERIDOS,CHOQUE,Otra-Conductor,NaN,LAS FLORES,URBANA,POINT (-75.57921612 6.172014741)

================================================================================
📄 ARCHIVO: historico_siniestros_bogota_d.c_-.csv (36.66 MB)
================================================================================
📌 Total de columnas: 16
📌 Lista de columnas:
   1. X
   2. Y
   3. OBJECTID
   4. FORMULARIO
   5. CODIGO_ACCIDENTE
   6. FECHA_OCURRENCIA_ACC
   7. ANO_OCURRENCIA_ACC
   8. DIRECCION
   9. GRAVEDAD
   10. CLASE_ACC
   11. LOCALIDAD
   12. FECHA_HORA_ACC
   13. LATITUD
   14. LONGITUD
   15. CIV
   16. PK_CALZADA

🔍 Primeras 2 filas de muestra:

,X,Y,OBJECTID,FORMULARIO,CODIGO_ACCIDENTE,FECHA_OCURRENCIA_ACC,ANO_OCURRENCIA_ACC,DIRECCION,GRAVEDAD,CLASE_ACC,LOCALIDAD,FECHA_HORA_ACC,LATITUD,LONGITUD,CIV,PK_CALZADA
0,-74.090924,4.693807,1,A000640275,4484660,2017/06/12 00:00:00+00,2017,AV AVENIDA BOYACA-CL 79 02,SOLO DANOS,CHOQUE,ENGATIVA,2017/06/12 05:30:00+00,4.693807,-74.090924,10006772.0,221236.0
1,-74.121000,4.603000,2,A001233353,10533499,2020/11/19 00:00:00+00,2020,CL 26 S- KR 50 02,CON HERIDOS,OTRO,PUENTE ARANDA,2020/11/19 02:05:00+00,4.603000,-74.121000,16004560.0,NaN

================================================================================
📄 ARCHIVO: incidentes_viales.csv (59.44 MB)
================================================================================
📌 Total de columnas: 18
📌 Lista de columnas:
   1. AÑO
   2. CBML
   3. CLASE_ACCIDENTE
   4. DIRECCION
   5. DIRECCION ENCASILLADA
   6. DISEÑO
   7. EXPEDIENTE
   8. FECHA_ACCIDENTE
   9. FECHA_ACCIDENTES
   10. GRAVEDAD_ACCIDENTE
   11. MES
   12. NRO_RADICADO
   13. NUMCOMUNA
   14. BARRIO
   15. COMUNA
   16. LOCATION
   17. X
   18. Y

🔍 Primeras 2 filas de muestra:

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÑO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
0,2015,1013.0,Caida Ocupante,CR 46 CL 43,CR 046 043 000 00000,Tramo de via,A000259731,21/10/2015 05:58:00,2015-10-21T10:58:00.000Z,Con heridos,10,1508668,10,Barrio Colón,La Candelaria,"[-75.5688011014, 6.24312304123]",834949.69,1182357.34
1,2015,1020.0,Choque,CR 43 A CL 29,CR 043 A 029 000 00000,Tramo de via,A000261725,05/11/2015 03:00:00,2015-11-05T08:00:00.000Z,Solo daños,11,1510621,10,San Diego,La Candelaria,"[-75.5693883283, 6.22870030622]",834880.17,1180762.02

================================================================================
📄 ARCHIVO: siniestralidad_2016_2024.csv (26.07 MB)
================================================================================
❌ Error al leer el archivo siniestralidad_2016_2024.csv: Error tokenizing data. C error: Expected 1 fields in line 7, saw 2



================================================================================
📄 ARCHIVO: siniestros_viales_consolidados_bogota_dc.xlsx (46.90 MB)
================================================================================
📌 Total de columnas: 10
📌 Lista de columnas:
   1. CODIGO_ACCIDENTE
   2. FECHA
   3. HORA
   4. GRAVEDAD
   5. CLASE
   6. CHOQUE
   7. OBJETO_FIJO
   8. DIRECCION
   9. CODIGO_LOCALIDAD
   10. DISENO_LUGAR

🔍 Primeras 2 filas de muestra:

,CODIGO_ACCIDENTE,FECHA,HORA,GRAVEDAD,CLASE,CHOQUE,OBJETO_FIJO,DIRECCION,CODIGO_LOCALIDAD,DISENO_LUGAR
0,4401438,01/01/2015,01:05:00,2,2,NaN,NaN,KR 64A-CL 2C 02,16,2
1,4401449,01/01/2015,05:50:00,2,3,NaN,NaN,AV AVENIDA DEL SUR-KR 65A 41,7,1

In [3]:
import pandas as pd

# Probar lectura especificando encoding='latin-1' y detectando el separador
try:
    df_sin = pd.read_csv('siniestralidad_2016_2024.csv', sep=None, engine='python', encoding='latin-1', nrows=50)
    print("✅ 'siniestralidad_2016_2024.csv' leído exitosamente:")
    print(f"📌 Total de columnas: {len(df_sin.columns)}")
    print("📌 Lista de columnas:")
    for idx, col in enumerate(df_sin.columns, 1):
        print(f"   {idx}. {col}")
except Exception as e:
    print("❌ Error en siniestralidad_2016_2024.csv:", e)

✅ 'siniestralidad_2016_2024.csv' leído exitosamente:
📌 Total de columnas: 10
📌 Lista de columnas:
   1. Código
   2. Fecha
   3. Tipo confirmado
   4. Dirección reporte
   5. Tipo clase de accidente
   6. Tipo clase de accidente.1
   7. Tipo confirmado.1
   8. Medio de reporte
   9. Numero vehículos
   10. Tipo de vehículos implicados

In [4]:
import pandas as pd
import numpy as np
import os

print("⌛ Iniciando el proceso ETL de consolidación ajustado...")

dfs_procesados = []

def normalizar_gravedad(val):
    if pd.isna(val): return "OTRO"
    val = str(val).upper()
    if "HERID" in val: return "CON HERIDOS"
    if "MUERT" in val or "FATAL" in val: return "CON MUERTOS"
    if "DAÑO" in val or "SOLO DAÑO" in val: return "SOLO DAÑOS"
    return "OTRO"

def normalizar_clase(val):
    if pd.isna(val): return "OTRO"
    val = str(val).upper()
    if "CHOQUE" in val: return "CHOQUE"
    if "ATROPELLO" in val: return "ATROPELLO"
    if "VOLCAMIENTO" in val: return "VOLCAMIENTO"
    if "CAIDA" in val or "CAÍDA" in val: return "CAIDA OCUPANTE"
    return "OTRO"

# 1. BUCARAMANGA
try:
    print("🔄 Procesando Bucaramanga...")
    df_buca = pd.read_csv('3._Accidentes_de_Transito_ocurridos_en_el_Municipio_de_Bucaramanga_20260926.csv', low_memory=False)
    df_buca_clean = pd.DataFrame()
    df_buca_clean['id_siniestro'] = df_buca['ORDEN'].astype(str)
    df_buca_clean['ciudad'] = 'Bucaramanga'
    df_buca_clean['fecha_hora'] = pd.to_datetime(df_buca['FECHA'], errors='coerce')
    df_buca_clean['anio'] = df_buca['AÑO']
    df_buca_clean['mes'] = df_buca['MES']
    df_buca_clean['dia_semana'] = df_buca['DÍA']
    df_buca_clean['hora'] = pd.to_datetime(df_buca['HORA'], format='%Y-%m-%dT%H:%M:%S.%f', errors='coerce').dt.hour
    df_buca_clean['gravedad'] = df_buca['GRAVEDAD'].apply(normalizar_gravedad)
    df_buca_clean['clase_accidente'] = 'OTRO'
    df_buca_clean['direccion'] = np.nan
    df_buca_clean['barrio_localidad'] = df_buca['BARRIO'].fillna(df_buca['COMUNA'])
    df_buca_clean['latitud'] = np.nan
    df_buca_clean['longitud'] = np.nan
    dfs_procesados.append(df_buca_clean)
    print(f"   ✅ Bucaramanga: {len(df_buca_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Bucaramanga: {e}")

# 2. BARRANQUILLA
try:
    print("🔄 Procesando Barranquilla...")
    df_baq = pd.read_csv('Accidentalidad_en_Barranquilla_20260926.csv', low_memory=False)
    df_baq_clean = pd.DataFrame()
    df_baq_clean['id_siniestro'] = [f"BAQ_{i}" for i in range(len(df_baq))]
    df_baq_clean['ciudad'] = 'Barranquilla'
    df_baq_clean['fecha_hora'] = pd.to_datetime(df_baq['FECHA_ACCIDENTE'], errors='coerce')
    df_baq_clean['anio'] = df_baq['AÑO_ACCIDENTE']
    df_baq_clean['mes'] = df_baq['MES_ACCIDENTE']
    df_baq_clean['dia_semana'] = df_baq['DIA_ACCIDENTE']
    df_baq_clean['hora'] = pd.to_datetime(df_baq['HORA_ACCIDENTE'], format='%I:%M:%S:%p', errors='coerce').dt.hour
    df_baq_clean['gravedad'] = df_baq['GRAVEDAD_ACCIDENTE'].apply(normalizar_gravedad)
    df_baq_clean['clase_accidente'] = df_baq['CLASE_ACCIDENTE'].apply(normalizar_clase)
    df_baq_clean['direccion'] = df_baq['SITIO_EXACTO_ACCIDENTE']
    df_baq_clean['barrio_localidad'] = np.nan
    df_baq_clean['latitud'] = np.nan
    df_baq_clean['longitud'] = np.nan
    dfs_procesados.append(df_baq_clean)
    print(f"   ✅ Barranquilla: {len(df_baq_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Barranquilla: {e}")

# 3. ENVIGADO
try:
    print("🔄 Procesando Envigado...")
    df_env = pd.read_csv('Accidentalidad_Municipio_de__Envigado_20260926.csv', low_memory=False)
    df_env_clean = pd.DataFrame()
    df_env_clean['id_siniestro'] = df_env['RADICADO'].astype(str)
    df_env_clean['ciudad'] = 'Envigado'
    df_env_clean['fecha_hora'] = pd.to_datetime(df_env['FECHA'], errors='coerce')
    df_env_clean['anio'] = df_env_clean['fecha_hora'].dt.year
    df_env_clean['mes'] = df_env_clean['fecha_hora'].dt.month
    df_env_clean['dia_semana'] = df_env['DÍA DE LA SEMANA']
    df_env_clean['hora'] = pd.to_datetime(df_env['HORA'], format='%I:%M:%S %p', errors='coerce').dt.hour
    df_env_clean['gravedad'] = df_env['GRAVEDAD'].apply(normalizar_gravedad)
    df_env_clean['clase_accidente'] = df_env['CLASE DE ACCIDENTE'].apply(normalizar_clase)
    df_env_clean['direccion'] = df_env['DIRECCIÓN']
    df_env_clean['barrio_localidad'] = df_env['BARRIO']
    df_env_clean['latitud'] = np.nan
    df_env_clean['longitud'] = np.nan
    dfs_procesados.append(df_env_clean)
    print(f"   ✅ Envigado: {len(df_env_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Envigado: {e}")

# 4. BOGOTÁ (Histórico CSV)
try:
    print("🔄 Procesando Bogotá (Histórico CSV)...")
    df_bog = pd.read_csv('historico_siniestros_bogota_d.c_-.csv', low_memory=False)
    df_bog_clean = pd.DataFrame()
    df_bog_clean['id_siniestro'] = df_bog['FORMULARIO'].fillna(df_bog['OBJECTID']).astype(str)
    df_bog_clean['ciudad'] = 'Bogotá'
    df_bog_clean['fecha_hora'] = pd.to_datetime(df_bog['FECHA_HORA_ACC'], errors='coerce')
    df_bog_clean['anio'] = df_bog['ANO_OCURRENCIA_ACC']
    df_bog_clean['mes'] = df_bog_clean['fecha_hora'].dt.month
    df_bog_clean['dia_semana'] = df_bog_clean['fecha_hora'].dt.day_name()
    df_bog_clean['hora'] = df_bog_clean['fecha_hora'].dt.hour
    df_bog_clean['gravedad'] = df_bog['GRAVEDAD'].apply(normalizar_gravedad)
    df_bog_clean['clase_accidente'] = df_bog['CLASE_ACC'].apply(normalizar_clase)
    df_bog_clean['direccion'] = df_bog['DIRECCION']
    df_bog_clean['barrio_localidad'] = df_bog['LOCALIDAD']
    df_bog_clean['latitud'] = df_bog['LATITUD']
    df_bog_clean['longitud'] = df_bog['LONGITUD']
    dfs_procesados.append(df_bog_clean)
    print(f"   ✅ Bogotá CSV: {len(df_bog_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Bogotá CSV: {e}")

# 5. MEDELLÍN (Incidentes Viales)
try:
    print("🔄 Procesando Medellín (Incidentes Viales)...")
    df_med = pd.read_csv('incidentes_viales.csv', low_memory=False)
    df_med_clean = pd.DataFrame()
    df_med_clean['id_siniestro'] = df_med['NRO_RADICADO'].fillna(df_med['EXPEDIENTE']).astype(str)
    df_med_clean['ciudad'] = 'Medellín'
    df_med_clean['fecha_hora'] = pd.to_datetime(df_med['FECHA_ACCIDENTES'], errors='coerce')
    df_med_clean['anio'] = df_med['AÑO']
    df_med_clean['mes'] = df_med['MES']
    df_med_clean['dia_semana'] = df_med_clean['fecha_hora'].dt.day_name()
    df_med_clean['hora'] = df_med_clean['fecha_hora'].dt.hour
    df_med_clean['gravedad'] = df_med['GRAVEDAD_ACCIDENTE'].apply(normalizar_gravedad)
    df_med_clean['clase_accidente'] = df_med['CLASE_ACCIDENTE'].apply(normalizar_clase)
    df_med_clean['direccion'] = df_med['DIRECCION']
    df_med_clean['barrio_localidad'] = df_med['BARRIO'].fillna(df_med['COMUNA'])
    df_med_clean['latitud'] = df_med['Y']
    df_med_clean['longitud'] = df_med['X']
    dfs_procesados.append(df_med_clean)
    print(f"   ✅ Medellín: {len(df_med_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Medellín: {e}")

# 6. SINIESTRALIDAD (2016-2024 CSV)
try:
    print("🔄 Procesando Siniestralidad (2016-2024)...")
    # Removido low_memory para compatibilidad con engine='python'
    df_sin = pd.read_csv('siniestralidad_2016_2024.csv', sep=None, engine='python', encoding='latin-1')
    df_sin_clean = pd.DataFrame()
    df_sin_clean['id_siniestro'] = df_sin['Código'].astype(str)
    df_sin_clean['ciudad'] = 'Nacional / Indefinido'
    df_sin_clean['fecha_hora'] = pd.to_datetime(df_sin['Fecha'], errors='coerce')
    df_sin_clean['anio'] = df_sin_clean['fecha_hora'].dt.year
    df_sin_clean['mes'] = df_sin_clean['fecha_hora'].dt.month
    df_sin_clean['dia_semana'] = df_sin_clean['fecha_hora'].dt.day_name()
    df_sin_clean['hora'] = df_sin_clean['fecha_hora'].dt.hour
    df_sin_clean['gravedad'] = df_sin['Tipo confirmado'].apply(normalizar_gravedad)
    df_sin_clean['clase_accidente'] = df_sin['Tipo clase de accidente'].apply(normalizar_clase)
    df_sin_clean['direccion'] = df_sin['Dirección reporte']
    df_sin_clean['barrio_localidad'] = np.nan
    df_sin_clean['latitud'] = np.nan
    df_sin_clean['longitud'] = np.nan
    dfs_procesados.append(df_sin_clean)
    print(f"   ✅ Siniestralidad 2016-2024: {len(df_sin_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Siniestralidad 2016-2024: {e}")

# 7. BOGOTÁ (Consolidado Excel)
try:
    print("🔄 Procesando Bogotá Consolidado (Excel)...")
    df_bog_xls = pd.read_excel('siniestros_viales_consolidados_bogota_dc.xlsx')
    df_bog_xls_clean = pd.DataFrame()
    df_bog_xls_clean['id_siniestro'] = [f"BOG_XLS_{i}" for i in range(len(df_bog_xls))]
    df_bog_xls_clean['ciudad'] = 'Bogotá'
    
    col_fecha = [c for c in df_bog_xls.columns if 'FECHA' in c.upper() or 'DATE' in c.upper()]
    fecha_col = col_fecha[0] if col_fecha else df_bog_xls.columns[0]
    
    df_bog_xls_clean['fecha_hora'] = pd.to_datetime(df_bog_xls[fecha_col], errors='coerce')
    df_bog_xls_clean['anio'] = df_bog_xls_clean['fecha_hora'].dt.year
    df_bog_xls_clean['mes'] = df_bog_xls_clean['fecha_hora'].dt.month
    df_bog_xls_clean['dia_semana'] = df_bog_xls_clean['fecha_hora'].dt.day_name()
    df_bog_xls_clean['hora'] = df_bog_xls_clean['fecha_hora'].dt.hour
    
    col_grav = [c for c in df_bog_xls.columns if 'GRAVEDAD' in c.upper()]
    df_bog_xls_clean['gravedad'] = df_bog_xls[col_grav[0]].apply(normalizar_gravedad) if col_grav else 'OTRO'
    
    col_clase = [c for c in df_bog_xls.columns if 'CLASE' in c.upper()]
    df_bog_xls_clean['clase_accidente'] = df_bog_xls[col_clase[0]].apply(normalizar_clase) if col_clase else 'OTRO'
    
    df_bog_xls_clean['direccion'] = np.nan
    df_bog_xls_clean['barrio_localidad'] = np.nan
    df_bog_xls_clean['latitud'] = np.nan
    df_bog_xls_clean['longitud'] = np.nan
    dfs_procesados.append(df_bog_xls_clean)
    print(f"   ✅ Bogotá Excel: {len(df_bog_xls_clean):,} registros")
except Exception as e:
    print(f"   ❌ Error en Bogotá Excel: {e}")

# CONSOLIDADO FINAL
df_consolidado = pd.concat(dfs_procesados, ignore_index=True)

print("\n" + "="*80)
print(f"🎉 CONSOLIDACIÓN COMPLETADA EXITOSAMENTE 🎉")
print(f"📊 Total de registros finales: {len(df_consolidado):,}")
print("="*80)

⌛ Iniciando el proceso ETL de consolidación ajustado...
🔄 Procesando Bucaramanga...
   ✅ Bucaramanga: 39,193 registros
🔄 Procesando Barranquilla...
   ✅ Barranquilla: 28,523 registros
🔄 Procesando Envigado...
   ✅ Envigado: 89,826 registros
🔄 Procesando Bogotá (Histórico CSV)...
   ✅ Bogotá CSV: 199,146 registros
🔄 Procesando Medellín (Incidentes Viales)...
   ✅ Medellín: 270,765 registros
🔄 Procesando Siniestralidad (2016-2024)...
   ✅ Siniestralidad 2016-2024: 371,003 registros
🔄 Procesando Bogotá Consolidado (Excel)...
   ✅ Bogotá Excel: 196,152 registros

================================================================================
🎉 CONSOLIDACIÓN COMPLETADA EXITOSAMENTE 🎉
📊 Total de registros finales: 1,194,608
================================================================================

In [5]:
import pymongo
from pymongo import MongoClient
import pandas as pd
import numpy as np

print("⏳ Conectando a MongoDB e iniciando la limpieza y carga masiva...")

client = MongoClient("mongodb://localhost:27017/")
db = client["db_siniestralidad_vial"]
collection = db["siniestros"]

# Limpiar colección si ya existía para evitar duplicados
collection.drop()

df_mongo = df_consolidado.copy()

# ==========================================
# 🧹 LIMPIEZA FINAL DE CALIDAD DE DATOS (QA)
# ==========================================

# 1. Limpiar Años (quitar saltos de línea "\r", decimales y convertir a entero puro)
df_mongo['anio'] = pd.to_numeric(df_mongo['anio'].astype(str).str.replace(r'\D', '', regex=True), errors='coerce')
df_mongo['anio'] = df_mongo['anio'].fillna(0).astype(int) # 0 para los no reportados

# 2. Unificar Días de la Semana (Inglés a Español y todo en mayúsculas)
dias_map = {
    'MONDAY': 'LUNES', 'TUESDAY': 'MARTES', 'WEDNESDAY': 'MIÉRCOLES',
    'THURSDAY': 'JUEVES', 'FRIDAY': 'VIERNES', 'SATURDAY': 'SÁBADO', 'SUNDAY': 'DOMINGO'
}
df_mongo['dia_semana'] = df_mongo['dia_semana'].astype(str).str.upper().str.strip()
df_mongo['dia_semana'] = df_mongo['dia_semana'].replace(dias_map)
df_mongo['dia_semana'] = df_mongo['dia_semana'].replace(['NAN', 'NAT', 'NONE', ''], 'NO REPORTADO')

# 3. Formatear fechas a String para compatibilidad BSON/JSON
df_mongo['fecha_hora'] = df_mongo['fecha_hora'].astype(str)

# ==========================================
# 📥 CARGA A MONGODB
# ==========================================
records = df_mongo.to_dict('records')
batch_size = 50000
total_records = len(records)

for i in range(0, total_records, batch_size):
    lote = records[i:i + batch_size]
    collection.insert_many(lote)
    print(f"   📥 Insertados {min(i + batch_size, total_records):,} de {total_records:,} registros...")

print("\n" + "="*80)
print("✅ ¡LIMPIEZA Y CARGA A MONGODB COMPLETADA CON ÉXITO!")
print(f"📌 Total de documentos guardados en MongoDB: {collection.count_documents({}):,}")
print("="*80)

⏳ Conectando a MongoDB e iniciando la limpieza y carga masiva...
   📥 Insertados 50,000 de 1,194,608 registros...
   📥 Insertados 100,000 de 1,194,608 registros...
   📥 Insertados 150,000 de 1,194,608 registros...
   📥 Insertados 200,000 de 1,194,608 registros...
   📥 Insertados 250,000 de 1,194,608 registros...
   📥 Insertados 300,000 de 1,194,608 registros...
   📥 Insertados 350,000 de 1,194,608 registros...
   📥 Insertados 400,000 de 1,194,608 registros...
   📥 Insertados 450,000 de 1,194,608 registros...
   📥 Insertados 500,000 de 1,194,608 registros...
   📥 Insertados 550,000 de 1,194,608 registros...
   📥 Insertados 600,000 de 1,194,608 registros...
   📥 Insertados 650,000 de 1,194,608 registros...
   📥 Insertados 700,000 de 1,194,608 registros...
   📥 Insertados 750,000 de 1,194,608 registros...
   📥 Insertados 800,000 de 1,194,608 registros...
   📥 Insertados 850,000 de 1,194,608 registros...
   📥 Insertados 900,000 de 1,194,608 registros...
   📥 Insertados 950,000 de 1,194,608 registros...
   📥 Insertados 1,000,000 de 1,194,608 registros...
   📥 Insertados 1,050,000 de 1,194,608 registros...
   📥 Insertados 1,100,000 de 1,194,608 registros...
   📥 Insertados 1,150,000 de 1,194,608 registros...
   📥 Insertados 1,194,608 de 1,194,608 registros...

================================================================================
✅ ¡LIMPIEZA Y CARGA A MONGODB COMPLETADA CON ÉXITO!
📌 Total de documentos guardados en MongoDB: 1,194,608
================================================================================